begMessages = [f'Begging made you',
               f'Woah coins magically appeared in front of you',
               f'Oh you poor little beggar, take this and leave',
               f'Begging eh? Take this ',
               f'Go buy some food with this and leave',
               f'Go away!',
               f'Sho! Sho!',
               f'The stranger did not gave you money but you found',
               f'Stop begging so much, it makes you look like a little baby',
               f'Imagine begging lol',
               f'Id give you a nasty look but you have already got one',
               f'You are a pizza burn on the roof of the world’s mouth',
               f'You’re so dense that light bends around you <a:i_coin',
               f'If you were going to be two-faced at least make one of them pretty',
               f"Someday you'll go far... and I hope you stay there",
               f"Stupidity's not a crime so you're free to go",
               f"The zoo called. They're wondering how you got out of your cage",
               f"I was hoping for a battle of wits but you appear to be unarmed",
               f"You are proof that evolution can go in reverse",
               f"Hey your village called - they want their idiot back",
               f"I'd slap you but I don't want to make your face look any better",
               f"Your so ugly Hello Kitty said goodbye to you",
               f"I'd smack you if it wasn't animal abuse",
               f"You’re impossible to underestimate",
               f"Once you embrace your value, talents and strengths, it neutralizes when others think less of you."
               ]